version: '3.8'

services:
  hybridqa-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=./app/chroma_data
    volumes:
      - ../chroma_data:/app/chroma_data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1